import type { Order } from "@/types";

export const mockOrders: Order[] = [
  {
    id: "1",
    orderNumber: "10045",
    date: "2025-04-15T14:30:00Z",
    status: "Delivered",
    items: [
      {
        id: "item1",
        name: "Organic Cotton Baby Onesie",
        price: 24.99,
        quantity: 2,
        image: "/baby-onesie.png",
      },
      {
        id: "item2",
        name: "Soft Baby Blanket",
        price: 34.99,
        quantity: 1,
        image: "/soft-baby-blanket.png",
      },
    ],
    subtotal: 84.97,
    shipping: 5.99,
    tax: 7.65,
    total: 98.61,
    shippingAddress: {
      name: "John Smith",
      street: "123 Main St",
      city: "Anytown",
      state: "CA",
      zip: "12345",
      country: "United States",
    },
    paymentMethod: "Credit Card",
    paymentDetails: {
      cardLast4: "4242",
      cardBrand: "Visa",
      expiryDate: "04/26",
    },
  },
  {
    id: "2",
    orderNumber: "10046",
    date: "2025-04-02T09:15:00Z",
    status: "Shipped",
    items: [
      {
        id: "item3",
        name: "Baby Bottle Set",
        price: 29.99,
        quantity: 1,
        image: "/baby-bottle-set.png",
      },
      {
        id: "item4",
        name: "Teething Toy",
        price: 12.99,
        quantity: 3,
        image: "/colorful-teething-toy.png",
      },
    ],
    subtotal: 68.96,
    shipping: 5.99,
    tax: 6.21,
    total: 81.16,
    shippingAddress: {
      name: "John Smith",
      street: "123 Main St",
      city: "Anytown",
      state: "CA",
      zip: "12345",
      country: "United States",
    },
    paymentMethod: "PayPal",
    paymentDetails: {
      cardLast4: "",
      cardBrand: "",
      expiryDate: "",
    },
  },
  {
    id: "3",
    orderNumber: "10047",
    date: "2025-03-20T16:45:00Z",
    status: "Processing",
    items: [
      {
        id: "item5",
        name: "Baby Monitor",
        price: 149.99,
        quantity: 1,
        image: "/placeholder.svg?key=3p2wr",
      },
    ],
    subtotal: 149.99,
    shipping: 0,
    tax: 13.5,
    total: 163.49,
    shippingAddress: {
      name: "John Smith",
      street: "123 Main St",
      city: "Anytown",
      state: "CA",
      zip: "12345",
      country: "United States",
    },
    paymentMethod: "Credit Card",
    paymentDetails: {
      cardLast4: "1234",
      cardBrand: "Mastercard",
      expiryDate: "09/25",
    },
  },
  {
    id: "4",
    orderNumber: "10048",
    date: "2025-03-10T11:20:00Z",
    status: "Delivered",
    items: [
      {
        id: "item6",
        name: "Baby Carrier",
        price: 89.99,
        quantity: 1,
        image: "/placeholder.svg?key=6hqwm",
      },
      {
        id: "item7",
        name: "Pacifier Set",
        price: 15.99,
        quantity: 2,
        image: "/pacifier-set.png",
      },
      {
        id: "item8",
        name: "Baby Shampoo",
        price: 9.99,
        quantity: 3,
        image: "/gentle-baby-shampoo.png",
      },
    ],
    subtotal: 151.94,
    shipping: 5.99,
    tax: 13.67,
    total: 171.6,
    shippingAddress: {
      name: "John Smith",
      street: "123 Main St",
      city: "Anytown",
      state: "CA",
      zip: "12345",
      country: "United States",
    },
    paymentMethod: "Credit Card",
    paymentDetails: {
      cardLast4: "5678",
      cardBrand: "Amex",
      expiryDate: "12/26",
    },
  },
];
